#!/usr/bin/env bash
#This a script that configure our ubuntu server to respect our arguments.
#look for output  in the nginx /var/www/html/index.nginx-debian.html

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
