#!/usr/bin/env bash
#This a script that configure our ubuntu server to respect our arguments.
#look for output  in the nginx /var/www/html/index.nginx-debian.html

sudo apt-get -y update
sudo apt-get -y install nginx

# Check if Nginx is listening on port 80
sudo ss -lnpt | grep ':80'

echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start

# Check if the index file contains the expected message
cat /var/www/html/index.nginx-debian.html
