#!/usr/bin/env bash
#Make it sweet and short
ln -sf /etc/nginx/sites-available/default  etc/nginx/sites-enabled/default
service  nginx restart
kill "$(pgrep 'nginx' | head -1)"#this cmd attemps to kill nginx process
