#!/usr/bin/env bash
#declare name and passphrase
KEY_NAME="school"
PASSPHRASE="betty"

#Generate the rsa key pair(PRIVATE KEY)
ssh-keygen -t rsa -b 4096 -N "$PASSPHRASE" -f $KEY_NAME
#Generate public key from the pk
ssh-keygen -y -f school -p betty > $KEYNAME.pub
